fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        enabled: true
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: htnk, priorities: [ html ] }
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    body_listener:
        decoders:
            json: fos_rest.decoder.json