security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        App\Entity\User:
            algorithm: argon2i


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
                # optional: if you're using multiple Doctrine entity
                # managers, this option defines which one to use
                # manager_name: 'customer'

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: 
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            guard:
                authenticators:
                    - App\Security\SecurityControllerAuthenticator

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/article, role: ROLE_USER }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
