easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    # ...
                    - { property: 'active' }
                    - { property: 'solution', type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }